######################################################################
# Automatically generated by qmake (2.01a) dom jan 9 11:59:08 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cell.h wifinetlist.h wlanman.h
SOURCES += cell.cpp main.cpp wifinetlist.cpp wlanman.cpp
RESOURCES += res.qrc
