######################################################################
# Automatically generated by qmake (2.01a) qua jan 5 20:56:45 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += wlanman.h \
    wifinetlist.h \
    cell.h
SOURCES += main.cpp wlanman.cpp \
    wifinetlist.cpp \
    cell.cpp
RESOURCES += res.qrc
